FROM ubuntu:19.10

LABEL SOFTWARE_NAME BUSCO 4.0.4
LABEL SOFTWARE_URL http://busco.ezlab.org/
LABEL MAINTAINER "Tom Harrop"
LABEL VERSION "BUSCO 4.0.4"

ENV DEBIAN_FRONTEND=noninteractive
ENV LC_ALL=C
ENV AUGUSTUS_CONFIG_PATH="/opt/augustus-3.3.3/config"
ENV BUSCO_CONFIG_FILE="/busco/config/config.ini"
ENV TOOLDIR="/tools"
ENV PATH="${PATH}:/blast/bin:/opt/augustus-3.3.3/bin:/opt/augustus-3.3.3/scripts:/busco/scripts"


# faster apt downloads
RUN . /etc/os-release && \
    echo "\
deb mirror://mirrors.ubuntu.com/mirrors.txt ${UBUNTU_CODENAME} main restricted universe multiverse \n\
deb mirror://mirrors.ubuntu.com/mirrors.txt ${UBUNTU_CODENAME}-updates main restricted universe multiverse \n\
deb mirror://mirrors.ubuntu.com/mirrors.txt ${UBUNTU_CODENAME}-backports main restricted universe multiverse \n\
deb mirror://mirrors.ubuntu.com/mirrors.txt ${UBUNTU_CODENAME}-security main restricted universe multiverse \n"\
    > mirror.txt

RUN mv /etc/apt/sources.list /etc/apt/sources.list.bak && \
        cat mirror.txt /etc/apt/sources.list.bak > /etc/apt/sources.list

# dependencies
RUN apt-get update && \
    apt-get install -y \
        autoconf \
        automake \
        bamtools \
        build-essential \
        git \
        hmmer \
        libbamtools-dev \
        libboost-iostreams-dev \
        libbz2-dev \
        libcurl3-dev \
        liblzma-dev \
        libncurses5-dev \
        libssl-dev \
        prodigal \
        python3 \
        python3-pip \
        software-properties-common \
        wget \
        zlib1g-dev

# use python3
RUN update-alternatives \
        --install /usr/local/bin/python \
        python \
        /usr/bin/python3 \
        1

WORKDIR "${TOOLDIR}"
# augustus dependencies
RUN git clone https://github.com/samtools/htslib.git "${TOOLDIR}/htslib"
WORKDIR "${TOOLDIR}/htslib"
RUN autoheader && autoconf && ./configure && make && make install

# augustus dependencies - bcftools
RUN git clone https://github.com/samtools/bcftools.git "${TOOLDIR}/bcftools" 
WORKDIR "${TOOLDIR}/bcftools" 
RUN autoheader && autoconf && ./configure && make && make install

# augustus dependencies - tabix
RUN git clone https://github.com/samtools/tabix.git "${TOOLDIR}/tabix" 
WORKDIR "${TOOLDIR}/tabix" 
RUN make

# augustus dependencies - samtools
RUN git clone https://github.com/samtools/samtools.git "${TOOLDIR}/samtools"
WORKDIR "${TOOLDIR}/samtools" 
RUN autoheader && autoconf -Wno-syntax && ./configure && make && make install

# install augustus
WORKDIR /
RUN mkdir /augustus && \
    wget -O "augustus.tar.gz" \
        http://bioinf.uni-greifswald.de/augustus/binaries/augustus-3.3.3.tar.gz && \
    tar -zxf augustus.tar.gz \
        -C /augustus \
        --strip-components 1 && \
    rm -f augustus.tar.gz
WORKDIR /augustus
RUN make && make install

# allow *writing* to the augustus config dir
RUN chmod -R 777 "${AUGUSTUS_CONFIG_PATH}"

# install blast 2.2.31
WORKDIR /
RUN wget -O "blast.tar.gz" \
        ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.2.31/ncbi-blast-2.2.31+-x64-linux.tar.gz && \
    mkdir /blast && \
    tar -zxf blast.tar.gz \
        -C /blast \
        --strip-components 1 && \
    rm -f blast.tar.gz

# install sepp
RUN git clone https://github.com/smirarab/sepp.git /sepp
WORKDIR /sepp
RUN git checkout -f 4.3.10 && \
    git submodule update --init --recursive && \
    python setup.py config && \
    python setup.py install

# install BUSCO
RUN /usr/bin/pip3 install biopython
RUN git clone https://gitlab.com/ezlab/busco.git /busco
WORKDIR busco
RUN git checkout -f  4.0.4 && \
    git submodule update --init --recursive && \
    python3 setup.py install && \
    mv "${BUSCO_CONFIG_FILE}" "${BUSCO_CONFIG_FILE}.default" && \
    busco_configurator.py \
        "${BUSCO_CONFIG_FILE}.default" \
        "${BUSCO_CONFIG_FILE}"

ENTRYPOINT ["/usr/local/bin/busco"]
