FROM ubuntu:19.10

LABEL SOFTWARE_NAME Racon v1.4.10
LABEL SOFTWARE_URL https://github.com/lbcb-sci/racon
LABEL MAINTAINER "Tom Harrop"
LABEL VERSION "Racon v1.4.10"

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y \
        apt-transport-https \
        build-essential \
        cmake \
        git \
        language-pack-en \
        lsb-release \
        nvidia-modprobe \
        python \
        software-properties-common \
        wget

RUN add-apt-repository -y ppa:graphics-drivers/ppa && \
    apt update && \
    apt install -y \
        nvidia-cuda-toolkit

#  nvidia-driver-430 \ ?

# download master
RUN git clone \
    https://github.com/lbcb-sci/racon.git \
    /racon
WORKDIR /racon
RUN git checkout 1.4.10
RUN git submodule update --init --recursive || true     # have to allow fail

# download release
# RUN wget -O "racon.tar.gz" \
#         --no-check-certificate \
#         https://github.com/lbcb-sci/racon/releases/download/1.4.7/racon-v1.4.7.tar.gz
# RUN tar -zxf racon.tar.gz \
#         --strip-components 1 && \
#     rm racon.tar.gz
# WORKDIR /racon

# build and install with cuda support
RUN mkdir build && cd build || exit 1 && \
    cmake \
        -DCMAKE_BUILD_TYPE=Release \
        -Dracon_build_tests=ON \
        -Dracon_build_wrapper=ON \
        -D CUDA_TOOLKIT_ROOT_DIR=/usr/lib/cuda \
        -Dracon_enable_cuda=ON \
        .. && \
    make && make install

ENV PATH="${PATH}:/racon/build/bin"
ENTRYPOINT ["/racon/build/bin/racon"]
